### ISSUE TITLE
Wanna Give Up Suda

### ISSUE THREAD

**Issue by HarsonYoung** [dxkite/suda#1]
According to database part of the document, I even copy that code but it still have an error!

`Declaration of HelloTable::onCreateStruct(suda\database\struct\TableStruct $struct): suda\database\struct\TableStruct must be compatible with suda\application\database\Table::onCreateStruct(suda\orm\TableStruct $table): suda\orm\TableStruct
`
Furthermore, when I try to using the latest version, I find there have a big change happening  in suda at least in logs. :(

**Comment by dxkite** [comment]
make sure use the latest veriosn of the documents, the database module only moved the namespace to a right part.  see more: https://dxkite.github.io/suda/ or just see the demo [HelloTable.php](https://github.com/dxkite/suda/blob/master/suda/resource/app/modules/welcome/share/table/HelloTable.php) (global replace `suda\orm` --> `suda\datatbase`  at [#d23ce92f](https://github.com/dxkite/suda/tree/v3.1.0) ,

**Comment by dxkite** [comment]
as usual, you may use the `suda\application\database\Table` witch with nothing changes compare with the pre version of suda ( the namespace will autocomplete by IDE), the demo is auto generate by suda with the lastest changes.
