### ISSUE TITLE
Hi, 在dxkite.cn 网站中出现访问错误

### ISSUE THREAD

**Issue by HttoHu** [dxkite/suda#2]
**主页是能显示的，点开文章就出现了**
```
TypeError 
0
2019-09-04 10:15:19 PRC
Return value of support\visitor\provider\UserSessionAwareProvider::getContext() must be an instance of support\visitor\Context, null returned
```
![image](https://user-images.githubusercontent.com/26004214/64220779-2851ad80-cefd-11e9-9271-0d2673a45009.png)

**Comment by HttoHu** [comment]
我尝试在**Edge, Google Chrome 和我的手机浏览器**上尝试
WIFI和移动网络都出现了该错误.

**Comment by dxkite** [comment]
晚上回去修复，网站的访客升级了代码， dxkite.cn的项目地址：https://github.com/dxkite/clomery
